import Buttscript from './show-more.js'
import Swipscript from './swiper.js'
import styles from '../scss/style.scss'
import buttonScripts from './button.js'
import buttonFeedback from './button-feedback.js'
import buttonApp from './button-app.js'
import animationScripts from './animation.js'
import showMoreButtomBig from './show-more-biggest.js'
